// import './bootstrap';
import '../../public/js/jquery-3.1.1.min.js';
import '../../public/js/popper.min.js';
import '../../public/js/bootstrap.js';
import '../../public/js/plugins/metisMenu/jquery.metisMenu.js';
import '../../public/js/plugins/slimscroll/jquery.slimscroll.min.js';
import '../../public/js/plugins/flot/jquery.flot.js';
import '../../public/js/plugins/flot/jquery.flot.tooltip.min.js';
import '../../public/js/plugins/flot/jquery.flot.spline.js';
import '../../public/js/plugins/flot/jquery.flot.resize.js';
import '../../public/js/plugins/flot/jquery.flot.pie.js';
